config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :highscores
  

  match '/spacedust/highscores', :to => 'highscores#index'

  root :to => "pages#home"
  
  match '/games', :to => 'pages#games'
    match '/spacedust', :to => 'pages#spacedust'
  match '/hobbies', :to => 'pages#hobbies'
  match '/reviews', :to => 'pages#reviews'
  match '/twitter', :to => 'pages#twitter'
  

end

app/models/highscore.rb
require_dependency 'secretstuff'

class Highscore < ActiveRecord::Base
  attr_accessor   :encrypted_hash
  attr_accessible :name, :score , :encrypted_hash
  
  validates :name,  :presence => true,
                   :length => {:maximum =>50}
                    
  validates :encrypted_hash,  :presence =>true               

  validate :encrypted_hash_must_be_correct
  
  def encrypted_hash_must_be_correct
    #secretKey = "Twas brillig, and the slithy toves. Did gyre and gimble in the wabe"
    inputString = self.name + self.score.to_s + SecretStuff::SECRET_KEY
    ehash = Digest::MD5.hexdigest(inputString)
    if self.encrypted_hash != ehash
      errors.add(:encrypted_hash,"Encryped hash incorrect")
    end
  end                     
                    
end

# == Schema Information
#
# Table name: highscores
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  score      :integer
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
  
  def new
  end

  def create # handles posts
    @highscore = Highscore.new(params[:highscore])
    respond_to do |format|
      if @highscore.save
        format.html { redirect_to(@highscore, :notice => 'Highscore was successfully created.') }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @highscore.errors, :status => :unprocessable_entity }
        #format.json  { render :json => @highscore.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show
    @highscore = Highscore.find(params[:id])
  end

  def index
    @high_scores = Highscore.find(:all, :limit => 10,
                                  :order => 'score desc')
    respond_to do |format|
      format.html  
      format.xml { render :xml => @high_scores }
      format.json { render :text => @high_scores }
      format.text {render "index" ,:layout => false}
  end
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
    @twitter = "http://twitter.com/#!/PolityAI"
    @facebook = "http://www.facebook.com/morganjpage"
  end

  def games
    @title = "Games"
  end
  
  
  
  def spacedust
    @title = "Space Dust"
    @high_scores = Highscore.find(:all, :limit => 10,
                                  :order => 'score desc')
    respond_to do |format|
      format.html  
  end  
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis
  def title #method definition
    base_title = "Morgan Page's Web Portal"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/highscores_helper.rb
module HighscoresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/highscores/index.html.erb
<h1>Top 100 high scores</h1>
<table>
<tr>
<th>Score</th>
<th>Full name</th>
</tr>
<% for high_score in @high_scores %>
<tr>
	<td><%=h high_score.score %></td>
<td><%=h high_score.name %></td>
</tr>
<% end %>
</table>
<br />

app/views/highscores/index.text.erb
<% for high_score in @high_scores %>
<%=h Time.at(high_score.score).gmtime.strftime('%M:%S') + "\t" + high_score.name %>
<% end %>

app/views/highscores/new.html.erb
<h1>Highscores#new</h1>
<p>Find me in app/views/highscores/new.html.erb</p>

app/views/highscores/show.html.erb
<%= @hignscore.name %>, <%= @hignscore.score %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Twitter", @twitter %></li>
      <li><%= link_to "Facebook", @facebook %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <header>
    <%= link_to image_tag("logo.png", :alt => "Sample App", :class => "round"),
    		root_path 
    %>
    <nav class="round">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Games", games_path %>
			<ul>
		    	<li><%= link_to "Space Dust", spacedust_path %></li>
		    	<li><%= link_to "Next...", '#' %></li>
		    </ul>        
		</li>
		
        <li><%= link_to "Hobbies", hobbies_path %>
			<ul>
		    	<li><%= link_to "Paragliding", '#' %></li>
		    	<li><%= link_to "Snowboarding", '#' %></li>
		    	<li><%= link_to "Walking", '#' %></li>
		    	<li><%= link_to "Music", '#' %></li>
		    </ul>        
        </li>
        
        <li><%= link_to "Reviews", reviews_path %>
			<ul>
		    	<li><%= link_to "Game Reviews", '#' %></li>
		    	<li><%= link_to "Model Reviews", '#' %></li>
		    </ul>        
        </li>
        
      </ul>
    </nav>
  </header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'	%>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print'	%>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%=title%> </title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		<div class="container">
		<%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      		<%= render 'layouts/footer' %>
      		<%= debug(params) if Rails.env.development? %>
    </div>
	</body>
</html>

app/views/pages/games.html.erb
<h1>Games</h1>

<p>
  This is page that lists all my games...
</p>

app/views/pages/hobbies.html.erb
<h1>Hobbies</h1>
<p>Hobbies page.</a></p>

app/views/pages/home.html.erb
<h1>Morgan Page's Home Page</h1>

<p>
	Welcome to my website. Hopefully over the coming months this website will fill up with 
	games that I have created, reviews of games other people have created and various other 
	stuff that I deem interesting enough to post here.
</p>

app/views/pages/reviews.html.erb
<h1>Reviews</h1>
<p>Reviews page...</p>

app/views/pages/spacedust.html.erb
<h1>Space Dust</h1>

<p>
  Stranded in the depths of space, constantly under attack by living alien spaceships...
  How long can you survive, how many aliens will you destroy before you become Space Dust!!!
</p>

<h2>High Score Table</h2>
<table>
<tr>
<th>Time Survived</th>
<th>Full name</th>
</tr>
<% for high_score in @high_scores %>
<tr>
	
	<td><%=h Time.at(high_score.score).gmtime.strftime('%R:%S') %></td>
	
	<td><%=h high_score.name %></td>





</tr>
<% end %>
</table>